<?php
$elastic_url = "http://54.152.150.176";
$elastic_port = "9200";
$elastic_full_path = $elastic_url.":".$elastic_port;
$elastic_index = "resoucespace-dev";
$elastic_prefix = "rs-";
$date_fields = array("Load Date","Subject Creation Date","File Last Modified","creation_date","disk_usage_last_updated");
$dont_pull = array(
  "Analog Media Location",
  "Bit Depth",
  "Camera Label",
  "Channels",
  "Color Mode",
  "Color Profile",
  "Creative Commons Attribution Name",
  "Creative Commons Attribution URL",
  "Creator Tool",
  "DAM Insertion User",
  "Digitized From",
  "File Last Modified",
  "File Last Modified By",
  "GPS Altitude",
  "GPS Altitude Ref",
  "GPS Latitude",
  "GPS Latitude Ref",
  "GPS Longitude",
  "GPS Longitude Ref",
  "Instance ID",
  "Load Date",
  "Marker Comments",
  "Marker Duration",
  "Marker Name",
  "Marker Qualifier / ID",
  "Marker Start",
  "Media Cataloger",
  "Production Notes",
  "Sample Rate",
  "Selection Approved",
  "Selection Qualifier",
  "Shot Angle",
  "Shot Duration",
  "Shot Movement",
  "Shot Size",
  "Video Aspect Ratio",
  "Video Codec",
  "Video Color Space",
  "Video Field Order",
  "Video Frame Rate",
  "Video Frame Size",
  "access",
  "colour_key",
  "created_by",
  "creation_date",
  "disk_usage",
  "disk_usage_last_updated",
  "expiry_notification_sent",
  "field12",
  "field8",
  "file_modified",
  "file_size",
  "geo_lat",
  "geo_long",
  "hit_count",
  "image_blue",
  "image_green",
  "image_red",
  "is_transcoding",
  "new_hit_count",
  "original_link",
  "original_size",
  "preview_attempts",
  "preview_extension",
  "preview_tweaks",
  "request_count",
  "thumb_height",
  "thumb_width",
  "field3"
);
?>
